
--X11 friendly error messages

local err = {}

err.error = {
	'BadRequest',
	'BadValue',
	'BadWindow',
	'BadPixmap',
	'BadAtom',
	'BadCursor',
	'BadFont',
	'BadMatch',
	'BadDrawable',
	'BadAccess',
	'BadAlloc',
	'BadColor',
	'BadGC',
	'BadIDChoice',
	'BadName',
	'BadLength',
	'BadImplementation',
}

err.major = {
	'CreateWindow',
	'ChangeWindowAttributes',
	'GetWindowAttributes',
	'DestroyWindow',
	'DestroySubwindows',
	'ChangeSaveSet',
	'ReparentWindow',
	'MapWindow',
	'MapSubwindows',
	'UnmapWindow',
	'UnmapSubwindows',
	'ConfigureWindow',
	'CirculateWindow',
	'GetGeometry',
	'QueryTree',
	'InternAtom',
	'GetAtomName',
	'ChangeProperty',
	'DeleteProperty',
	'GetProperty',
	'ListProperties',
	'SetSelectionOwner',
	'GetSelectionOwner',
	'ConvertSelection',
	'SendEvent',
	'GrabPointer',
	'UngrabPointer',
	'GrabButton',
	'UngrabButton',
	'ChangeActivePointerGrab',
	'GrabKeyboard',
	'UngrabKeyboard',
	'GrabKey',
	'UngrabKey',
	'AllowEvents',
	'GrabServer',
	'UngrabServer',
	'QueryPointer',
	'GetMotionEvents',
	'TranslateCoords',
	'WarpPointer',
	'SetInputFocus',
	'GetInputFocus',
	'QueryKeymap',
	'OpenFont',
	'CloseFont',
	'QueryFont',
	'QueryTextExtents',
	'ListFonts',
	'ListFontsWithInfo',
	'SetFontPath',
	'GetFontPath',
	'CreatePixmap',
	'FreePixmap',
	'CreateGC',
	'ChangeGC',
	'CopyGC',
	'SetDashes',
	'SetClipRectangles',
	'FreeGC',
	'ClearArea',
	'CopyArea',
	'CopyPlane',
	'PolyPoint',
	'PolyLine',
	'PolySegment',
	'PolyRectangle',
	'PolyArc',
	'FillPoly',
	'PolyFillRectangle',
	'PolyFillArc',
	'PutImage',
	'GetImage',
	'PolyText8',
	'PolyText16',
	'ImageText8',
	'ImageText16',
	'CreateColormap',
	'FreeColormap',
	'CopyColormapAndFree',
	'InstallColormap',
	'UninstallColormap',
	'ListInstalledColormaps',
	'AllocColor',
	'AllocNamedColor',
	'AllocColorCells',
	'AllocColorPlanes',
	'FreeColors',
	'StoreColors',
	'StoreNamedColor',
	'QueryColors',
	'LookupColor',
	'CreateCursor',
	'CreateGlyphCursor',
	'FreeCursor',
	'RecolorCursor',
	'QueryBestSize',
	'QueryExtension',
	'ListExtensions',
	'ChangeKeyboardMapping',
	'GetKeyboardMapping',
	'ChangeKeyboardControl',
	'GetKeyboardControl',
	'Bell',
	'ChangePointerControl',
	'GetPointerControl',
	'SetScreenSaver',
	'GetScreenSaver',
	'ChangeHosts',
	'ListHosts',
	'SetAccessControl',
	'SetCloseDownMode',
	'KillClient',
	'RotateProperties',
	'ForceScreenSaver',
	'SetPointerMapping',
	'GetPointerMapping',
	'SetModifierMapping',
	'GetModifierMapping',
	[127] = 'NoOperation',
	--extensions
	[142] = 'BIG-REQUESTS',
	[151] = 'Composite',
	[152] = 'DAMAGE',
	[134] = 'DOUBLE-BUFFER',
	[131] = 'DPMS',
	[136] = 'DRI2',
	[153] = 'GLX',
	[137] = 'Generic Event Extension',
	[128] = 'MIT-SCREEN-SAVER',
	[139] = 'MIT-SHM',
	[149] = 'RANDR',
	[135] = 'RECORD',
	[148] = 'RENDER',
	[146] = 'SECURITY',
	[153] = 'SGI-GLX',
	[138] = 'SHAPE',
	[143] = 'SYNC',
	[133] = 'X-Resource',
	[145] = 'XC-MISC',
	[147] = 'XFIXES',
	[130] = 'XFree86-DGA',
	[129] = 'XFree86-VidModeExtension',
	[150] = 'XINERAMA',
	[140] = 'XInputExtension',
	[144] = 'XKEYBOARD',
	[141] = 'XTEST',
	[132] = 'XVideo',
}

err.minor = {
	--TODO
}

--make an error message from a xcb_generic_error_t
function err.format(e)
	local err_name = err.error[e.error_code] or 'unknown'
	local maj_name = err.major[e.major_code] or 'unknown'
	local min_name = err.minor[e.minor_code] or 'unknown'
	return string.format('XCB error: %d (%s), maj: %d (%s), min: %d (%s), res_id: %d, sequence: %d',
		e.error_code, err_name, e.major_code, maj_name, e.minor_code, min_name, e.resource_id, e.sequence)
end

return err
